# Generated by Django 2.1 on 2020-05-14 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_orderupdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderupdate',
            name='id',
        ),
        migrations.AddField(
            model_name='orderupdate',
            name='update_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
