# Generated by Django 2.1 on 2020-05-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20200514_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderupdate',
            name='update_id',
        ),
        migrations.AddField(
            model_name='orderupdate',
            name='id',
            field=models.AutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
