# Generated by Django 2.1 on 2020-05-15 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20200514_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='camount',
            field=models.IntegerField(default=0),
        ),
    ]
